sudo: required
services: 
  - docker

before_install:
  - docker build -t thsnphm11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thsnphm11/react-test npm test

after_success:
  - docker build -t thsnphm11/multi-client ./client
  - docker build -t thsnphm11/multi-nginx ./nginx
  - docker build -t thsnphm11/multi-server ./server
  - docker build -t thsnphm11/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push thsnphm11/multi-client
  - docker push thsnphm11/multi-nginx
  - docker push thsnphm11/multi-server
  - docker push thsnphm11/multi-worker