sudo: required
services: 
  - docker

before_install:
  - docker build -t phamthaison/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phamthaison/react-test npm test

after_success:
  - docker build -t phamthaison/multi-client ./client
  - docker build -t phamthaison/multi-nginx ./nginx
  - docker build -t phamthaison/multi-server ./server
  - docker build -t phamthaison/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push phamthaison/multi-client
  - docker push phamthaison/multi-nginx
  - docker push phamthaison/multi-server
  - docker push phamthaison/multi-worker